In [2]:
import numpy as np
from sklearn.datasets import load_iris

In [7]:
iris = load_iris()
print(np.unique(iris.target))
X, y = iris['data'], iris['target']  # 0 1 2중 하나 선택

[0 1 2]


In [8]:
from sklearn.svm import SVC

In [11]:
svc = SVC(probability=True)
svc.fit(X, y)
svc.score(X, y) # 97%

0.9733333333333334

In [13]:
print(svc.predict([X[0]])) # X[0]를 넣었을 때 y값(target)0,1,2중 무엇인가! # predict_proba, decision_function을 다 해서 이미 나온것 # 아래는 그냥 확인차 해본 것. predict는 이 두 가지를 거쳐서 나오게 된다
print(svc.predict_proba([X[0]])) # 0일 확률, 1일 확률, 2일 확률  -> 0이 높아서 0으로 나온다. 어떤 값을 어떤 수준으로 확인하고 있음
print(svc.decision_function([X[0]])) # data에 따라 가중치 값이 다르게 나옴 -> 값이 중요하지 않고(판단하는 기준값) 값의 크기가 높은 것이 나옴. 여기선 0

[0]
[[0.97764236 0.01421891 0.00813872]]
[[ 2.23543749  1.16096255 -0.25650709]]


In [20]:
v=svc.decision_function(X) # 각 행마다 0,1,2에 대해 어떻게 판단했는지
m = np.argmax(v, axis=1) # 각 행에서 가장 큰 값의 위치를 반환
(y == m).sum()/len(m)

0.9733333333333334

In [28]:
v2=svc.predict_proba(X)
# print(np.sum(v2, axis=1)) # 개별 값은 확률이기 때문에 각 행의 합은 1 (확률이라서)
m2 = np.argmax(v2, axis=1)
(y == m2).sum()/len(y)

0.98

In [31]:
X[0]

array([5.1, 3.5, 1.4, 0.2])

In [ ]:
m2 ==svc.predict(X) # decision_function이 하는것